version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    # Defaults
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced Go linter (includes gosimple)
    - unused        # Check for unused code

    # Additional recommended linters
    - misspell      # Find commonly misspelled words
    - gosec         # Security problems
    - goconst       # Find repeated strings that could be constants
    - gocyclo       # Cyclomatic complexity
    - dupl          # Code clone detection
    - copyloopvar   # Check for pointers to enclosing loop variables (replaces exportloopref)
    - gocritic      # Opinionated Go linter
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Find unused function parameters
    - prealloc      # Find slice declarations that could be preallocated
    - nolintlint    # Reports ill-formed or insufficient nolint directives

  disable:
    - funlen        # Too strict for TUI code
    - gocognit      # Similar to gocyclo
    - lll           # Line length check - too annoying
