run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    # Defaults
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced Go linter
    - typecheck     # Type-check Go code
    - unused        # Check for unused code

    # Additional recommended linters
    - gofmt         # Check code is gofmt-ed
    - goimports     # Check imports are formatted
    - misspell      # Find commonly misspelled words
    - gosec         # Security problems
    - goconst       # Find repeated strings that could be constants
    - gocyclo       # Cyclomatic complexity
    - dupl          # Code clone detection
    - exportloopref # Check for pointers to enclosing loop variables
    - gocritic      # Opinionated Go linter
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Find unused function parameters
    - prealloc      # Find slice declarations that could be preallocated
    - nolintlint    # Reports ill-formed or insufficient nolint directives

  disable:
    - funlen        # Too strict for TUI code
    - gocognit      # Similar to gocyclo
    - lll           # Line length check - too annoying

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - fmt.Fprintf
      - fmt.Fprintln

  govet:
    enable-all: true
    disable:
      - shadow # Too many false positives

  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  gosec:
    excludes:
      - G104 # Audit errors not checked - handled by errcheck
      - G304 # File path provided as taint input - needed for AWS configs

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - hugeParam # AWS SDK has large structs

  revive:
    severity: warning
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst

    # Ignore TUI styling code complexity
    - path: internal/tui/
      linters:
        - gocyclo
        - goconst

    # Allow fmt.Printf in TUI code
    - path: internal/tui/
      text: "fmt.Sprintf can be replaced"

  # Show all issues
  exclude:
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*print(f|ln)?|os\\.(Un)?Setenv). is not checked"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
