version: 1

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: a9s
    binary: a9s
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X github.com/keanuharrell/a9s/cmd.Version={{.Version}}
    flags:
      - -trimpath

archives:
  - id: a9s
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# Homebrew formula configuration
brews:
  - name: a9s
    repository:
      owner: keanuharrell
      name: homebrew-a9s
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: "https://github.com/keanuharrell/a9s"
    description: "🚀 The k9s for AWS - Interactive Terminal UI"
    license: "MIT"
    skip_upload: auto
    test: |
      system "#{bin}/a9s --version"
    install: |
      bin.install "a9s"
    dependencies:
      - name: git

# Snapcraft configuration  
snapcrafts:
  - name: a9s
    publish: true
    summary: The k9s for AWS - Interactive Terminal UI
    description: |
      a9s is the k9s for AWS - a powerful Terminal UI that provides an intuitive way to manage AWS infrastructure.
      
      Features:
      - Interactive Terminal UI with real-time data
      - EC2 instance management (list, start, stop)
      - IAM security auditing and risk assessment
      - S3 bucket analysis and cleanup recommendations
      - Multi-profile and multi-region support
      - JSON and table output formats
      
      Perfect for DevOps engineers, SREs, and anyone managing AWS infrastructure.
    grade: stable
    confinement: strict
    license: MIT
    base: core22
    apps:
      a9s:
        command: a9s
        plugs: ["home", "network"]
    
# Nix packages
nix:
  - name: a9s
    repository:
      owner: keanuharrell
      name: nur-a9s
      token: "{{ .Env.NIX_GITHUB_TOKEN }}"
    homepage: "https://github.com/keanuharrell/a9s"
    description: "Interactive Terminal UI for AWS infrastructure management"
    license: "mit"
    skip_upload: auto

# AUR package for Arch Linux
aurs:
  - name: a9s-bin
    homepage: "https://github.com/keanuharrell/a9s"
    description: "The k9s for AWS - Interactive Terminal UI for AWS infrastructure management"
    maintainers:
      - 'Keanu Harrell <keanu@example.com>'
    license: MIT
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: 'ssh://aur@aur.archlinux.org/a9s-bin.git'
    skip_upload: auto

# Docker images
dockers:
  - image_templates:
      - "ghcr.io/keanuharrell/a9s:{{ .Version }}-amd64"
      - "ghcr.io/keanuharrell/a9s:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description=Interactive Terminal UI for AWS infrastructure management
      - --label=org.opencontainers.image.url=https://github.com/keanuharrell/a9s
      - --label=org.opencontainers.image.source=https://github.com/keanuharrell/a9s
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
    goarch: amd64

  - image_templates:
      - "ghcr.io/keanuharrell/a9s:{{ .Version }}-arm64"
      - "ghcr.io/keanuharrell/a9s:latest-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description=Interactive Terminal UI for AWS infrastructure management
      - --label=org.opencontainers.image.url=https://github.com/keanuharrell/a9s
      - --label=org.opencontainers.image.source=https://github.com/keanuharrell/a9s
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/keanuharrell/a9s:{{ .Version }}"
    image_templates:
      - "ghcr.io/keanuharrell/a9s:{{ .Version }}-amd64"
      - "ghcr.io/keanuharrell/a9s:{{ .Version }}-arm64"
  - name_template: "ghcr.io/keanuharrell/a9s:latest"
    image_templates:
      - "ghcr.io/keanuharrell/a9s:latest-amd64"
      - "ghcr.io/keanuharrell/a9s:latest-arm64"