version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: a9s
    binary: a9s
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/keanuharrell/a9s/cmd.Version={{.Version}}
      - -X github.com/keanuharrell/a9s/cmd.BuildTime={{.Date}}
    flags:
      - -trimpath

archives:
  - id: a9s
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- .Arch }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  disable: true  # semantic-release handles changelog

release:
  prerelease: auto
  mode: append  # Append assets to existing release

# Homebrew tap
brews:
  - repository:
      owner: keanuharrell
      name: homebrew-a9s
      token: "{{ .Env.GITHUB_TOKEN }}"
    homepage: "https://github.com/keanuharrell/a9s"
    description: "The k9s for AWS - Interactive Terminal UI for AWS"
    license: "MIT"
    skip_upload: auto
    install: |
      bin.install "a9s"
    test: |
      system "#{bin}/a9s", "--version"
