version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: a9s
    binary: a9s
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/keanuharrell/a9s/cmd.Version={{.Version}}
      - -X github.com/keanuharrell/a9s/cmd.BuildTime={{.Date}}
    flags:
      - -trimpath

archives:
  - id: a9s
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- .Arch }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'README'
  groups:
    - title: 'Features'
      regexp: '^feat:'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^fix:'
      order: 1
    - title: 'Others'
      order: 999

# Homebrew formula configuration
brews:
  - repository:
      owner: keanuharrell
      name: homebrew-a9s
      token: "{{ .Env.GITHUB_TOKEN }}"
    homepage: "https://github.com/keanuharrell/a9s"
    description: "The k9s for AWS - Interactive Terminal UI for AWS infrastructure management"
    license: "MIT"
    skip_upload: auto
    test: |
      system "#{bin}/a9s --version"
    install: |
      bin.install "a9s"
    dependencies:
      - name: git
        type: optional

# Docker images
dockers:
  - image_templates:
      - "ghcr.io/keanuharrell/a9s:{{ .Version }}-amd64"
      - "ghcr.io/keanuharrell/a9s:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description=Interactive Terminal UI for AWS infrastructure management
      - --label=org.opencontainers.image.url=https://github.com/keanuharrell/a9s
      - --label=org.opencontainers.image.source=https://github.com/keanuharrell/a9s
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
    goarch: amd64

  - image_templates:
      - "ghcr.io/keanuharrell/a9s:{{ .Version }}-arm64"
      - "ghcr.io/keanuharrell/a9s:latest-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description=Interactive Terminal UI for AWS infrastructure management
      - --label=org.opencontainers.image.url=https://github.com/keanuharrell/a9s
      - --label=org.opencontainers.image.source=https://github.com/keanuharrell/a9s
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/keanuharrell/a9s:{{ .Version }}"
    image_templates:
      - "ghcr.io/keanuharrell/a9s:{{ .Version }}-amd64"
      - "ghcr.io/keanuharrell/a9s:{{ .Version }}-arm64"
  - name_template: "ghcr.io/keanuharrell/a9s:latest"
    image_templates:
      - "ghcr.io/keanuharrell/a9s:latest-amd64"
      - "ghcr.io/keanuharrell/a9s:latest-arm64"